# Site settings
author: Dakota States
title: When There's Nothing Left to Learn...
header-img: img/home-bg.png
email: dakota.states@gmail.com
copyright_name: Dakota States
description: > # this means to ignore newlines until "baseurl:"
  The Future of Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dakotastates

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
